# -*- coding: utf-8 -*-
"""DMA_research.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aueDvTJ-0iaxKW_EExi53hhegTNr9Bsj
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)
sns.set(style="whitegrid")

"""Uploading Dataset"""

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("airlines_flights_data.csv")
print("Shape of dataset:", df.shape)
df.head()

"""Basic cleaning and checks"""

print(df.info())
print("\nMissing values:\n", df.isnull().sum())
print("\nBasic statistics:\n", df.describe())

"""**Exploratory Data Analysis (EDA) + Visualizations**

Market share of airlines

“In this dataset, Vistara has the highest share, followed by IndiGo…”

“However, real-world DGCA data shows IndiGo as the actual market leader.”
"""

airline_counts = df["airline"].value_counts()

plt.figure(figsize=(8,8))
plt.pie(airline_counts, labels=airline_counts.index, autopct='%1.1f%%',
        startangle=140, colors=sns.color_palette("Set3"))
plt.title("Airline Market Share (Dataset)", fontsize=14)
plt.show()

print("Airline flight counts in dataset:\n", airline_counts)

"""distribution of ticket prices"""

plt.figure(figsize=(8,5))
sns.histplot(df["price"], bins=50, kde=True, color="skyblue")
plt.title("Distribution of Ticket Prices", fontsize=14)
plt.xlabel("Price")
plt.ylabel("Frequency")
plt.show()

"""Airlines vs average prices"""

plt.figure(figsize=(12,6))
ax = sns.barplot(x="airline", y="price", data=df, estimator=np.mean, ci=None, palette="Set2")
plt.title("Average Ticket Price per Airline", fontsize=14)
plt.xticks(rotation=45)

for p, airline in zip(ax.patches, df["airline"].unique()):
    ax.annotate(f"{airline}\n₹{p.get_height():.0f}",
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='bottom', fontsize=8, color="black", xytext=(0, 5),
                textcoords="offset points")
plt.show()

"""Price Distribution by Airline

* Shows how ticket prices vary within each airline.

* Useful to analyze which airline has high variance (premium vs budget).
"""

plt.figure(figsize=(12,6))
sns.violinplot(x="airline", y="price", data=df, palette="Set2")
plt.title("Price Distribution by Airline", fontsize=14)
plt.xticks(rotation=45)
plt.show()

"""Insight: Budget airlines (IndiGo, SpiceJet) have tight clusters, premium airlines (Vistara, Air India) show wider spread."""



"""Stops vs price"""

plt.figure(figsize=(6,4))
sns.boxplot(x="stops", y="price", data=df, palette="Set3")
plt.title("Impact of Stops on Price", fontsize=14)
plt.show()

"""Days left vs price"""

plt.figure(figsize=(8,5))
sns.scatterplot(x="days_left", y="price", data=df, hue="airline", alpha=0.6, palette="tab10")
plt.title("Ticket Price vs Days Left for Booking", fontsize=14)
plt.xlabel("Days Left")
plt.ylabel("Price")
plt.legend(title="Airline", bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

"""Heatmap - average price by city pairs"""

route_counts = df.groupby(["source_city", "destination_city"]).size().unstack(fill_value=0)
plt.figure(figsize=(10,8))
sns.heatmap(route_counts, cmap="YlGnBu", annot=False)
plt.title("Route Popularity Heatmap", fontsize=14)
plt.show()

"""ML Models (Regression Example — Predict Price)"""

f_sample = df.sample(frac=0.2, random_state=42)
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=50,   # fewer trees
    max_depth=10,      # limit depth
    n_jobs=-1,         # use all CPU cores
    random_state=42
)
model.fit(X_train, y_train)


from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor

lr = LinearRegression()
lr.fit(X_train, y_train)

dt = DecisionTreeRegressor(max_depth=10, random_state=42)
dt.fit(X_train, y_train)

"""Artificial Neural Network (ANN) for Price Prediction"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from sklearn.preprocessing import StandardScaler


scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)


X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Build ANN model
ann = Sequential()
ann.add(Dense(128, input_dim=X_train.shape[1], activation='relu'))
ann.add(Dropout(0.3))
ann.add(Dense(64, activation='relu'))
ann.add(Dropout(0.2))
ann.add(Dense(32, activation='relu'))
ann.add(Dense(1, activation='linear'))  # Regression output


ann.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])

history = ann.fit(X_train, y_train, validation_split=0.2, epochs=20, batch_size=64, verbose=1)

# Evaluate
ann_eval = ann.evaluate(X_test, y_test, verbose=0)
print("ANN MAE:", ann_eval[1])

# Predictions
y_pred_ann = ann.predict(X_test)

# Compare RF vs ANN performance
print("\nRandom Forest R²:", r2_score(y_test, model.predict(X_test)))
print("ANN R²:", r2_score(y_test, y_pred_ann))